package dangerorganization.nogomet;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Momcad implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nazivPrve;
   private java.lang.String nazivDruge;
   private java.lang.Integer goloviPrve;
   private java.lang.Integer goloviDruge;

   public Momcad()
   {
   }

   public java.lang.String getNazivPrve()
   {
      return this.nazivPrve;
   }

   public void setNazivPrve(java.lang.String nazivPrve)
   {
      this.nazivPrve = nazivPrve;
   }

   public java.lang.String getNazivDruge()
   {
      return this.nazivDruge;
   }

   public void setNazivDruge(java.lang.String nazivDruge)
   {
      this.nazivDruge = nazivDruge;
   }

   public java.lang.Integer getGoloviPrve()
   {
      return this.goloviPrve;
   }

   public void setGoloviPrve(java.lang.Integer goloviPrve)
   {
      this.goloviPrve = goloviPrve;
   }

   public java.lang.Integer getGoloviDruge()
   {
      return this.goloviDruge;
   }

   public void setGoloviDruge(java.lang.Integer goloviDruge)
   {
      this.goloviDruge = goloviDruge;
   }

   public Momcad(java.lang.String nazivPrve, java.lang.String nazivDruge,
         java.lang.Integer goloviPrve, java.lang.Integer goloviDruge)
   {
      this.nazivPrve = nazivPrve;
      this.nazivDruge = nazivDruge;
      this.goloviPrve = goloviPrve;
      this.goloviDruge = goloviDruge;
   }

}