package dangerorganization.nogomet;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Momcad implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ime")
   private java.lang.String ime;
   @org.kie.api.definition.type.Label(value = "golovi")
   private java.lang.Integer golovi;

   public Momcad()
   {
   }

   public java.lang.String getIme()
   {
      return this.ime;
   }

   public void setIme(java.lang.String ime)
   {
      this.ime = ime;
   }

   public java.lang.Integer getGolovi()
   {
      return this.golovi;
   }

   public void setGolovi(java.lang.Integer golovi)
   {
      this.golovi = golovi;
   }

   public Momcad(java.lang.String ime, java.lang.Integer golovi)
   {
      this.ime = ime;
      this.golovi = golovi;
   }

}