package dangerorganization.nogomet;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrvaMomcad implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PrvaMomcad() {
    }

}